server:
  port: 8081
spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/qunfx?characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      mybatis-plus:
        mapper-locations: classpath:com/zs/user01/mapper
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379
    main:
      allow-bean-definition-overriding: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"